image: node:15.0

services:
  - docker:dind

stages:
  - build
#  - deploy
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

#before_script:
#  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  image: node:14.17.4
  script:
    - yarn  install
    - yarn build-storybook
    #- yarn build

  artifacts:
    paths:
      - storybook-static
      #- out
