image: node:15.0

services:
  - docker:dind

stages:
  - build
  - deploy
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

#before_script:
#  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  image: node:14.17.4
  script:
    - npm  install
    #- yarn build-storybook
    - npm build

  artifacts:
    paths:
     # - storybook-static
      - out

deploy:
  stage: deploy
  dependencies:
     - build
  before_script: 
     - ls -la
     #- ls -la storybook-static
     - ls -la out
     - mkdir -p ~/.ssh     
     - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa     
     - chmod 600 ~/.ssh/id_rsa     
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config' 
       
  script:
    - ls -la
    - scp -r /builds/f-case/marketplace-front/out/* deployer@$DEPLOY_SERVER:/data/estatum-front/front 
  environment:
    name: production
  only:
     - development
