stages:
  - build-app
#  - build-image

build app:
  stage: build-app
  image: node:8
  script:
    - yarn
    - yarn lint
    - yarn build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - .next
      - build
