stages:
  - build-app
#  - build-image

build app:
  stage: build-app
  image: node:14.17.4
  script:
    - yarn  install
    - npm build-storybook
    #- yarn build
  cache:
    paths:
      - node_modules
  artifacts:
    paths:
      - .next
      - build
