image: node:latest

stages:
   - build
   - deploy
variables:
  DEPLOY_FOLDER: /data/front #/data/test-sas-realestate-front/
  DEPLOY_SERVER: 185.98.83.65  # 84.201.179.232 #185.98.83.65
  DEPLOY_USER: deployer
  DEPLOY_PORT: 20071 #22 #20064



build:
  stage: build
  script:
     - apk add --no-cache --virtual .build-deps alpine-sdk python \
     - yarn install --production --silent \
     - apk del .build-deps
     #- yarn install
     #- yarn run build_prod
     - mkdir public
    #- ls -la
    #- ls -la dist
     - cp -rf dist/* public
     - ls -la public
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  dependencies:
     - build
  before_script: 
     - ls -la public
     - mkdir -p ~/.ssh     
     - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa     
     - chmod 600 ~/.ssh/id_rsa     
     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config' 
       
  script:
  #    - ls -la
   #   - ls -la ../checkest.ru
    #  - ls -la src/app
     - ls -la public
 #    - ssh deployer@$DEPLOY_SERVER -p DEPLOY_PORT "ls -la $DEPLOY_FOLDER"
     #- ssh deployer@$DEPLOY_SERVER "rm -r /data/checkest-front/front/*"
     #- ssh deployer@$DEPLOY_SERVER "mkdir /data/checkest-front/front"
     #- ssh deployer@$DEPLOY_SERVER "ls -la /data/checkest-front/front"
     - scp -P 20071 -r public/* deployer@$DEPLOY_SERVER:$DEPLOY_FOLDER 
 #    - ssh deployer@$DEPLOY_SERVER -p DEPLOY_PORT "ls -la $DEPLOY_FOLDER"
  environment:
    name: production
