version: '3.7'

networks:
  marketplace:
    name: marketplace
services:
  market-front:
    container_name: marketplace-front
    image: market-front:latest
    networks:
      - marketplace
    restart: always
    volumes:
      - .keys:/app/keys
      - .env:/app/env
  market-proxy:
    container_name: proxy
    image: nginx:1.20.1
    networks:
      - marketplace
    restart: always
    ports:
      - 443:443
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/proxy.conf:ro
