import { IDeveloperTabsData } from "../../tabs/Developer";
import { DEVELOPER_ABOUT_PARAGRAPHS, DEVELOPER_CONTACTS, DEVELOPER_MASS_MEDIA_ARTICLES, DEVELOPER_OWNERS_COMPANY, DEVELOPER_OWNER_GOVERMENT, DEVELOPER_PRIMARY_ACTIVITIES, DEVELOPER_REQUISITS, DEVELOPER_RISKS, DEVELOPER_SECONDARY_ACTIVITIES, DEVELOPER_STATISTICS } from "../../tabs/Developer/config";

export const DEVELOPER_TABS_DATA: IDeveloperTabsData = {
    about: DEVELOPER_ABOUT_PARAGRAPHS,
    contacts: DEVELOPER_CONTACTS,
    requisits: DEVELOPER_REQUISITS,
    owners: {
        company: DEVELOPER_OWNERS_COMPANY,
        goverment: DEVELOPER_OWNER_GOVERMENT,
    },
    activities: {
        primary: DEVELOPER_PRIMARY_ACTIVITIES,
        secondary: DEVELOPER_SECONDARY_ACTIVITIES,
    },
    news: DEVELOPER_MASS_MEDIA_ARTICLES,
    statistics: DEVELOPER_STATISTICS,
    risks: DEVELOPER_RISKS
}